#!/bin/bash

# ITMT workaround for linux-clear
echo 0 > /proc/sys/kernel/sched_itmt_enabled

# Use fair deadline scheduler for all drives
echo mq-deadline > /sys/block/sda/queue/scheduler
echo mq-deadline > /sys/block/sdb/queue/scheduler
echo mq-deadline > /sys/block/sdc/queue/scheduler

# Load Ethernet driver
modprobe r8169

# Configure Ethernet
ip link set netc0 mtu 1500
ip link set lo mtu 9999
systemctl start netctl@ppp0

# Get rid of junk ethernet engineers think is good
ethtool -K netc0 tx-nocache-copy off
ethtool -K netc0 tso off
ethtool -K netc0 gro off
ethtool -K netc0 tcp-segmentation-offload off

# WiFi country hack (enables 2.4GHz CH13)
iw reg set GY

sleep 10

# Start Gallium router's firewall and networking services
systemctl start shorewall
sleep 3

pihole restartdns
systemctl restart cloudflared-dns

# Limit console spamming by dmesg
dmesg -n 1

# Run debloat3 for the first time
/usr/bin/debloat3

# Disable any excessive power saving
tlp ac
nvidia-smi -pl 30

# Cache in memory some stuff that crontab uses a lot.
cp /usr/bin/checkwifi /dev/shm/
cp /usr/bin/checkwifi2 /dev/shm/
cp /usr/bin/ga-netrec /dev/shm/
cp /usr/bin/ga-prio /dev/shm
cd /home/mcs/snapServer/twf

# Start Lastsnap Vanilla
sudo -u mcs /home/mcs/snapServer/twf/watchdog.sh ul
sudo -u mcs /home/mcs/snapServer/twf/watchdog.sh -d

# Enable write cache
hdparm -W 1 /dev/sda
