#!/bin/bash
# Part of yagoply's LSV-Gallium Utilities
# For some reason these don't work if put inside the main script.

set -a
skip="true"
command="save-all flush"
sudo -Eu mcs /home/mcs/snapServer/twf/watchdog -l
sudo -Eu mcs /home/mcs/snapServer/twf/watchdog -c
sleep 8
command="save-off"
sudo -Eu mcs /home/mcs/snapServer/twf/watchdog -c
sleep .5
command="kick @a Rebooting the server. We'll be back in a few minutes."
sudo -Eu mcs /home/mcs/snapServer/twf/watchdog -c